services:
  - type: web
    name: n8n
    env: node
    plan: free
    region: oregon
    repo: https://github.com/vivek09-bit/n8n
    branch: main
    buildCommand: pnpm install --frozen-lockfile && pnpm --filter=cli run build
    startCommand: pnpm --filter=cli start
    envVars:
      - key: TURBO_REPO_IS_CI
        value: true
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 10000
      - key: DB_TYPE
        value: sqlite
      - key: WEBHOOK_URL
        value: https://n8n-1rzu.onrender.com
